tweak logger and echo messages in ArchiveXXX scripts

diff --git a/scripts/ArchiveTeeFiles b/scripts/ArchiveTeeFiles
--- a/scripts/ArchiveTeeFiles
+++ b/scripts/ArchiveTeeFiles
@@ -8,8 +8,8 @@ set myname = ArchiveTeeFiles
 set setup = ~nrts/scripts/ScriptSetup
 if (! -e $setup ) then
     set message = "missing $setup"
-    logger -t $myname"[$$]" -p local0.info "$message"
-    echo "${myname}: $message"
+    logger -t ${myname} $myname"[$$]" -p local0.info "$message"
+    echo "${myname} $message"
     goto failure
 endif
 source $setup
@@ -25,13 +25,13 @@ endif
 set lock   = /var/tmp/$myname.lock
 filelock $lock $$
 if ($status != 0) then
-    if ($debug) logger -t $myname"[$$]" -p local0.info "another instance already active"
+    if ($debug) logger -t ${myname} $myname"[$$]" -p local0.info "another instance already active"
     exit 0
 endif
 
 
 if (($#argv != 2) && ($#argv != 3)) then
-    logger -t $myname"[$$]" -p local0.info "bad command line"
+    logger -t ${myname} $myname"[$$]" -p local0.info "bad command line"
     echo "usage: $myname raw_root_dir ms_root_dir [stage_root_dir]"
     goto failure
 endif
@@ -39,16 +39,16 @@ endif
 set RawArchiveDir = $argv[1]
 if (! -d $RawArchiveDir) then
     set message = "missing $RawArchiveDir"
-    logger -t $myname"[$$]" -p local0.info "$message"
-    echo "${myname}: $message"
+    logger -t ${myname} $myname"[$$]" -p local0.info "$message"
+    echo "${myname} $message"
     goto failure
 endif
 
 set MSArchiveDir = $argv[2]
 if (! -d $MSArchiveDir) then
     set message = "missing $MSArchiveDir"
-    logger -t $myname"[$$]" -p local0.info "$message"
-    echo "${myname}: $message"
+    logger -t ${myname} $myname"[$$]" -p local0.info "$message"
+    echo "${myname} $message"
     goto failure
 endif
 
@@ -59,25 +59,25 @@ else
     set StageDir = $argv[3]
     if (! -d $StageDir) then
         set message = "missing $StageDir"
-        logger -t $myname"[$$]" -p local0.info "$message"
-        echo "${myname}: $message"
+        logger -t ${myname} $myname"[$$]" -p local0.info "$message"
+        echo "${myname} $message"
         goto failure
     endif
 endif
 
-if ($debug) logger -t $myname"[$$]" -p local0.info "begin"
+if ($debug) logger -t ${myname} $myname"[$$]" -p local0.info "begin"
 
 # Process each site listed in the Systems file
 
 set systems = $NRTS_HOME/etc/Systems
 if (! -e $systems) then
-    logger -t $myname"[$$]" -p local0.info "missing $systems file"
+    logger -t ${myname} $myname"[$$]" -p local0.info "missing $systems file"
     goto failure
 endif
 
 set SiteList = `stripcat $systems`
 if ($status != 0) then
-    logger -t $myname"[$$]" -p local0.info "stripcat $systems FAILED"
+    logger -t ${myname} $myname"[$$]" -p local0.info "stripcat $systems FAILED"
     goto failure
 endif
 
@@ -87,39 +87,39 @@ foreach site ($SiteList)
     set raw_archive = $RawArchiveDir/$site
 
     if (! -d $tee) then
-        if ($debug) logger -t $myname"[$$]" -p local0.info "Skipping $site. No tee dir found ($tee)."
+        if ($debug) logger -t ${myname} $myname"[$$]" -p local0.info "Skipping $site. No tee dir found ($tee)."
         continue
     endif
 
     if (! -d $raw_archive) then
         set command = "mkdir $raw_archive"
-        if ($debug) logger -t $myname"[$$]" -p local0.info "$command"
+        if ($debug) logger -t ${myname} $myname"[$$]" -p local0.info "$command"
         $command
         if ($status != 0) then
             set message = "can't $command"
-            logger -t $myname"[$$]" -p local0.info "$message"
-            echo "${myname}: $message"
+            logger -t ${myname} $myname"[$$]" -p local0.info "$message"
+            echo "${myname} $message"
             goto failure
         endif
     endif
 
     set command = "GzipTeeFiles $tee"
-    if ($debug) logger -t $myname"[$$]" -p local0.info "$command"
+    if ($debug) logger -t ${myname} $myname"[$$]" -p local0.info "$command"
     $command
 
     if ($use_staging_dir == 1) then
        set stage = $StageDir/$site
        set command = "StageGzFiles $tee $stage"
        if (-d $stage) then
-           if ($debug) logger -t $myname"[$$]" -p local0.info "$command"
+           if ($debug) logger -t ${myname} $myname"[$$]" -p local0.info "$command"
            $command
        else
-           if ($debug) logger -t $myname"[$$]" -p local0.info "${stage} not found. Skipping: $command"
+           if ($debug) logger -t ${myname} $myname"[$$]" -p local0.info "${stage} not found. Skipping: $command"
        endif
     endif
 
     set command = "ArchiveGzFiles $tee $site $RawArchiveDir $MSArchiveDir"
-    if ($debug) logger -t $myname"[$$]" -p local0.info "$command"
+    if ($debug) logger -t ${myname} $myname"[$$]" -p local0.info "$command"
     $command
 
 end
@@ -127,11 +127,11 @@ end
 # Normal exit
 
 success:
-if ($debug) logger -t $myname"[$$]" -p local0.info "completed OK"
+if ($debug) logger -t ${myname} $myname"[$$]" -p local0.info "completed OK"
 exit 0
 
 failure:
-logger -t $myname"[$$]" -p local0.info "exit 1"
+logger -t ${myname} $myname"[$$]" -p local0.info "exit 1"
 exit 1
 
 # Revision History
