change syslog facility from user.info to local0.info

diff --git a/scripts/ArchiveGzFiles b/scripts/ArchiveGzFiles
--- a/scripts/ArchiveGzFiles
+++ b/scripts/ArchiveGzFiles
@@ -12,7 +12,7 @@ set myname = ArchiveGzFiles
 set setup  = ~nrts/scripts/ScriptSetup
 if (! -e $setup ) then
     set message = "missing $setup"
-    logger -t $myname"[$$]" -p user.info "$message"
+    logger -t $myname"[$$]" -p local0.info "$message"
     echo "${myname}: $message"
     goto failure
 endif
@@ -26,7 +26,7 @@ else
     set debug = 0
 endif
 
-if ($debug) logger -t $myname"[$$]" -p user.info "begin"
+if ($debug) logger -t $myname"[$$]" -p local0.info "begin"
 
 # Command line setup
 
@@ -42,7 +42,7 @@ endif
 
 if ($error) then
     set message = "bad command line, error $error"
-    logger -t $myname"[$$]" -p user.info "$message"
+    logger -t $myname"[$$]" -p local0.info "$message"
     echo "${myname}: $message"
     echo "usage: $myname srcdir dstdir"
     goto failure
@@ -52,13 +52,13 @@ endif
 
 foreach dir ($srcdir $dstroot)
     if (! -d $dir) then
-        logger -t $myname"[$$]" -p user.info "ERROR: no such dir $dir"
+        logger -t $myname"[$$]" -p local0.info "ERROR: no such dir $dir"
         set error = 1
     endif
 end
 
 if ($error) then
-    logger -t $myname"[$$]" -p user.info "ERROR: required directories are missing"
+    logger -t $myname"[$$]" -p local0.info "ERROR: required directories are missing"
     goto failure
 endif
 
@@ -66,7 +66,7 @@ endif
 
 cd $srcdir
 if ($status != 0) then
-    logger -t $myname"[$$]" -p user.info "ERROR: can't chdir $srcdir"
+    logger -t $myname"[$$]" -p local0.info "ERROR: can't chdir $srcdir"
     goto failure
 endif
 
@@ -91,20 +91,20 @@ foreach file ([4-9]???????????????????????.gz [4-9]???????????????????????.GZ)
             set destdir = $dstroot/$date
             if (! -d $destdir) then
                 set command = "mkdir -p $destdir"
-                if ($debug) logger -t $myname"[$$]" -p user.info "$command"
+                if ($debug) logger -t $myname"[$$]" -p local0.info "$command"
                 $command
             endif
             if (! -d $destdir) then
-                logger -t $myname"[$$]" -p user.info "ERROR: missing $destdir"
+                logger -t $myname"[$$]" -p local0.info "ERROR: missing $destdir"
                 rm $dummy
                 goto failure
             endif
             set destpath = `uniqpath suflen=3 $file $destdir`
             set command = "cp -p $file $destpath"
-            if ($debug) logger -t $myname"[$$]" -p user.info "$command"
+            if ($debug) logger -t $myname"[$$]" -p local0.info "$command"
             $command
             if ($status != 0) then
-                logger -t $myname"[$$]" -p user.info "FAILED: $command"
+                logger -t $myname"[$$]" -p local0.info "FAILED: $command"
                 rm $dummy
                 goto failure
             endif
@@ -121,12 +121,12 @@ foreach file ([4-9]???????????????????????.gz [4-9]???????????????????????.GZ)
             set command  = "$cmd < $filepath >>! $msfile"
             echo $command >>! ${IDA_ARCHIVE_MS_DIR}/converted-to-ms
 
-            if ($debug) logger -t $myname"[$$]" -p user.info "$command"
+            if ($debug) logger -t $myname"[$$]" -p local0.info "$command"
 
             # send stderr output to log file.
             ($cmd < $filepath >>! $msfile) >>& ${IDA_ARCHIVE_MS_DIR}/converted-to-ms
             if ($status != 0) then 
-                logger -t $myname"[$$]" -p user.info "FAILED: $command"
+                logger -t $myname"[$$]" -p local0.info "FAILED: $command"
                 rm $dummy
                 rm -rf $msfile
                 goto failure
@@ -134,15 +134,15 @@ foreach file ([4-9]???????????????????????.gz [4-9]???????????????????????.GZ)
             #echo $msout >>! ${IDA_ARCHIVE_MS_DIR}/converted-to-ms
 
             set command = "chmod 444 $destpath"
-            if ($debug) logger -t $myname"[$$]" -p user.info "$command"
+            if ($debug) logger -t $myname"[$$]" -p local0.info "$command"
             $command
             set command = "dupchk $destpath"
-            if ($debug) logger -t $myname"[$$]" -p user.info "$command"
+            if ($debug) logger -t $myname"[$$]" -p local0.info "$command"
             $command
-            if ($status != 0) logger -t $myname"[$$]" -p user.info "WARNING: $command FAILED (ignored)"
+            if ($status != 0) logger -t $myname"[$$]" -p local0.info "WARNING: $command FAILED (ignored)"
         end
         set command = "rm -f $file"
-        if ($debug) logger -t $myname"[$$]" -p user.info "$command"
+        if ($debug) logger -t $myname"[$$]" -p local0.info "$command"
         $command
     endif
 end
@@ -159,34 +159,34 @@ foreach day ($msdays)
 	set sitedayms = ${site}-${year}-${jday}.ms
 	set dayms = ${IDA_ARCHIVE_MS_DIR}/${lsite}/${day}/${sitedayms}
 
-    if ($debug) logger -t $myname"[$$]" -p user.info "Moving previous run files into TEMP dir..."
+    if ($debug) logger -t $myname"[$$]" -p local0.info "Moving previous run files into TEMP dir..."
     # first lets move existing files to TEMP dir
     mkdir -p ${IDA_ARCHIVE_MS_DIR}/${lsite}/${day}/TEMP
     mv -f ${IDA_ARCHIVE_MS_DIR}/${lsite}/${day}/*.${year}.${jday} ${IDA_ARCHIVE_MS_DIR}/${lsite}/${day}/TEMP/ >& /dev/null
     # TODO: SOme error checking perhaps...
 
-    if ($debug) logger -t $myname"[$$]" -p user.info "Prepping whole-day ms file for run through dataselect..."
+    if ($debug) logger -t $myname"[$$]" -p local0.info "Prepping whole-day ms file for run through dataselect..."
 	# now run through dataselect
 	# -Sd - split data on day boundaries
 	# -Ps - prune data at the sample level and collapse overlaps
 	# -ts - start time
 	# -te - end time
 	set command = "dataselect -Sd -Ps -ts ${year}.${jday}.00.00.00 -te ${year}.${jday}.23.59.59.999 -A ${IDA_ARCHIVE_MS_DIR}/${lsite}/%Y/%j/%n.%s.%l.%c.%Y.%j $dayms"
-	if ($debug) logger -t $myname"[$$]" -p user.info "$command"
+	if ($debug) logger -t $myname"[$$]" -p local0.info "$command"
 	$command
 	if ($status != 0) then
-		logger -t $myname"[$$]" -p user.info "FAILED: $command"
+		logger -t $myname"[$$]" -p local0.info "FAILED: $command"
 		goto failure
 	endif
 	echo $command >>! ${IDA_ARCHIVE_MS_DIR}/processed-by-dataselect
 	
     set command = "msi -S ${IDA_ARCHIVE_MS_DIR}/${lsite}/${day}/II.${site}.*.*.${year}.${jday}"
     set invfn   = ${IDA_ARCHIVE_MS_DIR}/${lsite}/${day}/inventory
-	if ($debug) logger -t $myname"[$$]" -p user.info "$command '>!' $invfn"
+	if ($debug) logger -t $myname"[$$]" -p local0.info "$command '>!' $invfn"
 	$command >! $invfn
     set savestat = $status
 	if ($savestat != 0) then
-		logger -t $myname"[$$]" -p user.info "FAILED: [retcode: $savestat] $command '>!' $invfn"
+		logger -t $myname"[$$]" -p local0.info "FAILED: [retcode: $savestat] $command '>!' $invfn"
 		goto failure
 	endif
 	echo "$command '>!' $invfn" >>! ${IDA_ARCHIVE_MS_DIR}/processed-by-dataselect
@@ -197,10 +197,10 @@ end
 # Normal exit
 
 success:
-if ($debug) logger -t $myname"[$$]" -p user.info "completed OK"
+if ($debug) logger -t $myname"[$$]" -p local0.info "completed OK"
 exit 0
 
 failure:
-logger -t $myname"[$$]" -p user.info "exit 1"
+logger -t $myname"[$$]" -p local0.info "exit 1"
 exit 1
 
diff --git a/scripts/ArchiveTeeFiles b/scripts/ArchiveTeeFiles
--- a/scripts/ArchiveTeeFiles
+++ b/scripts/ArchiveTeeFiles
@@ -9,7 +9,7 @@ set myname = ArchiveTeeFiles
 set setup = ~nrts/scripts/ScriptSetup
 if (! -e $setup ) then
     set message = "missing $setup"
-    logger -t $myname"[$$]" -p user.info "$message"
+    logger -t $myname"[$$]" -p local0.info "$message"
     echo "${myname}: $message"
     goto failure
 endif
@@ -26,13 +26,13 @@ endif
 set lock   = /var/tmp/$myname.lock
 filelock $lock $$
 if ($status != 0) then
-    if ($debug) logger -t $myname"[$$]" -p user.info "another instance already active"
+    if ($debug) logger -t $myname"[$$]" -p local0.info "another instance already active"
     exit 0
 endif
 
 
 if ($#argv != 1) then
-    logger -t $myname"[$$]" -p user.info "bad command line"
+    logger -t $myname"[$$]" -p local0.info "bad command line"
     echo "usage: $myname archive_dir"
     goto failure
 endif
@@ -40,24 +40,24 @@ endif
 set ArchiveDir = $argv[1]
 if (! -d $ArchiveDir) then
     set message = "missing $ArchiveDir"
-    logger -t $myname"[$$]" -p user.info "$message"
+    logger -t $myname"[$$]" -p local0.info "$message"
     echo "${myname}: $message"
     goto failure
 endif
 
-if ($debug) logger -t $myname"[$$]" -p user.info "begin"
+if ($debug) logger -t $myname"[$$]" -p local0.info "begin"
 
 # Process each site listed in the Systems file
 
 set systems = /usr/nrts/etc/Systems
 if (! -e $systems) then
-    logger -t $myname"[$$]" -p user.info "missing $systems file"
+    logger -t $myname"[$$]" -p local0.info "missing $systems file"
     goto failure
 endif
 
 set SiteList = `stripcat $systems`
 if ($status != 0) then
-    logger -t $myname"[$$]" -p user.info "stripcat $systems FAILED"
+    logger -t $myname"[$$]" -p local0.info "stripcat $systems FAILED"
     goto failure
 endif
 
@@ -67,29 +67,29 @@ foreach site ($SiteList)
     set archive = $ArchiveDir/$site
     if (! -d $archive) then
         set command = "mkdir $archive"
-        if ($debug) logger -t $myname"[$$]" -p user.info "$command"
+        if ($debug) logger -t $myname"[$$]" -p local0.info "$command"
         $command
         if ($status != 0) then
             set message = "can't $command"
-            logger -t $myname"[$$]" -p user.info "$message"
+            logger -t $myname"[$$]" -p local0.info "$message"
             echo "${myname}: $message"
             goto failure
         endif
     endif
 
     set command = "GzipTeeFiles $tee"
-    if ($debug) logger -t $myname"[$$]" -p user.info "$command"
+    if ($debug) logger -t $myname"[$$]" -p local0.info "$command"
     $command
 
     set stage = /ida/stage/$site
     if (-d $stage) then
         set command = "StageGzFiles $tee $stage"
-        if ($debug) logger -t $myname"[$$]" -p user.info "$command"
+        if ($debug) logger -t $myname"[$$]" -p local0.info "$command"
         $command
     endif
 
     set command = "ArchiveGzFiles $tee $archive"
-    if ($debug) logger -t $myname"[$$]" -p user.info "$command"
+    if ($debug) logger -t $myname"[$$]" -p local0.info "$command"
     $command
 
 end
@@ -97,11 +97,11 @@ end
 # Normal exit
 
 success:
-if ($debug) logger -t $myname"[$$]" -p user.info "completed OK"
+if ($debug) logger -t $myname"[$$]" -p local0.info "completed OK"
 exit 0
 
 failure:
-logger -t $myname"[$$]" -p user.info "exit 1"
+logger -t $myname"[$$]" -p local0.info "exit 1"
 exit 1
 
 # Revision History
diff --git a/scripts/GzipTeeFiles b/scripts/GzipTeeFiles
--- a/scripts/GzipTeeFiles
+++ b/scripts/GzipTeeFiles
@@ -10,7 +10,7 @@ set myname = GzipTeeFiles
 set setup  = ~nrts/scripts/ScriptSetup
 if (! -e $setup ) then
     set message = "missing $setup"
-    logger -t $myname"[$$]" -p user.info "$message"
+    logger -t $myname"[$$]" -p local0.info "$message"
     echo "${myname}: $message"
     goto failure
 endif
@@ -24,7 +24,7 @@ else
     set debug = 0
 endif
 
-if ($debug) logger -t $myname"[$$]" -p user.info "begin"
+if ($debug) logger -t $myname"[$$]" -p local0.info "begin"
 
 # Command line setup
 
@@ -37,7 +37,7 @@ endif
 
 if ($error) then
     set message = "bad command line, error $error"
-    logger -t $myname"[$$]" -p user.info "$message"
+    logger -t $myname"[$$]" -p local0.info "$message"
     echo "${myname}: $message"
     echo "usage: $myname teedir"
     goto failure
@@ -51,7 +51,7 @@ set LockFile = $TeeDir/lock
 # Nothing to do if there isn't a tee directory
 
 if (! -d $TeeDir) then
-    if ($debug) logger -t $myname"[$$]" -p user.info "no such tee dir $TeeDir"
+    if ($debug) logger -t $myname"[$$]" -p local0.info "no such tee dir $TeeDir"
     goto success
 endif
 
@@ -60,14 +60,14 @@ endif
 filelock $LockFile $$
 if ($status != 0) then
     set active = `cat $LockFile`
-    if ($debug) logger -t $myname"[$$]" -p user.info "$TeeDir locked by process $active"
+    if ($debug) logger -t $myname"[$$]" -p local0.info "$TeeDir locked by process $active"
     goto success
 endif
 
 # Nothing to do if the STOP flag is set in the tee directory
 
 if (-e $StopFlag) then
-    if ($debug) logger -t $myname"[$$]" -p user.info "quit: $TeeDir STOP flag set"
+    if ($debug) logger -t $myname"[$$]" -p local0.info "quit: $TeeDir STOP flag set"
     goto success
 endif
 
@@ -78,14 +78,14 @@ set tmp = /tmp/$myname.$$
 /bin/ls [4-9]??????????????????????? >& $tmp
 if ($status != 0) then
     rm $tmp
-    if ($debug) logger -t $myname"[$$]" -p user.info "no uncompressed files found in $TeeDir"
+    if ($debug) logger -t $myname"[$$]" -p local0.info "no uncompressed files found in $TeeDir"
     goto success
 endif
 
 set NumFiles = `cat $tmp | wc -l`
 if ($NumFiles <= 1) then
     rm $tmp
-    if ($debug) logger -t $myname"[$$]" -p user.info "no uncompressed files found in $TeeDir"
+    if ($debug) logger -t $myname"[$$]" -p local0.info "no uncompressed files found in $TeeDir"
     goto success
 endif
 
@@ -96,32 +96,32 @@ rm $tmp
 # Compress each file in the list
 
 @ count = 0
-if ($debug) logger -t $myname"[$$]" -p user.info "compressing files in $TeeDir"
+if ($debug) logger -t $myname"[$$]" -p local0.info "compressing files in $TeeDir"
 if ($status == 0) then
     foreach file ($UncompressedFileList)
         set output = $file.gz
         rm -f $output
         set command = "gzip $file"
-        if ($debug) logger -t $myname"[$$]" -p user.info "$command"
+        if ($debug) logger -t $myname"[$$]" -p local0.info "$command"
         $command
         if (-e $file && -e $output) then
-            logger -t $myname"[$$]" -p user.info "$command failed"
+            logger -t $myname"[$$]" -p local0.info "$command failed"
             rm -f $output
             goto failure
         endif
         @ count++
     end
 endif
-if ($debug) logger -t $myname"[$$]" -p user.info "$count files compressed in $TeeDir"
+if ($debug) logger -t $myname"[$$]" -p local0.info "$count files compressed in $TeeDir"
 
 # Normal exit
 
 success:
-if ($debug) logger -t $myname"[$$]" -p user.info "completed OK"
+if ($debug) logger -t $myname"[$$]" -p local0.info "completed OK"
 exit 0
 
 failure:
-logger -t $myname"[$$]" -p user.info "exit 1"
+logger -t $myname"[$$]" -p local0.info "exit 1"
 exit 1
 
 # Revision History
diff --git a/scripts/StageGzFiles b/scripts/StageGzFiles
--- a/scripts/StageGzFiles
+++ b/scripts/StageGzFiles
@@ -12,7 +12,7 @@ set myname = StageGzFiles
 set setup  = ~nrts/scripts/ScriptSetup
 if (! -e $setup ) then
     set message = "missing $setup"
-    logger -t $myname"[$$]" -p user.info "$message"
+    logger -t $myname"[$$]" -p local0.info "$message"
     echo "${myname}: $message"
     goto failure
 endif
@@ -26,7 +26,7 @@ else
     set debug = 0
 endif
 
-if ($debug) logger -t $myname"[$$]" -p user.info "begin"
+if ($debug) logger -t $myname"[$$]" -p local0.info "begin"
 
 # Command line setup
 
@@ -40,25 +40,25 @@ endif
 
 if ($error) then
     set message = "bad command line, error $error"
-    logger -t $myname"[$$]" -p user.info "$message"
+    logger -t $myname"[$$]" -p local0.info "$message"
     echo "${myname}: $message"
     echo "usage: $myname srcdir dstdir"
     goto failure
 endif
 
-if ($debug) logger -t $myname"[$$]" -p user.info "srcdir=$srcdir dstdir=$dstdir"
+if ($debug) logger -t $myname"[$$]" -p local0.info "srcdir=$srcdir dstdir=$dstdir"
 
 # Nothing to do if the directories don't exist
 
 foreach dir ($srcdir $dstdir)
     if (! -d $dir) then
-        logger -t $myname"[$$]" -p user.info "ERROR: no such dir $dir"
+        logger -t $myname"[$$]" -p local0.info "ERROR: no such dir $dir"
         set error = 1
     endif
 end
 
 if ($error) then
-    logger -t $myname"[$$]" -p user.info "ERROR: required directories are missing"
+    logger -t $myname"[$$]" -p local0.info "ERROR: required directories are missing"
     goto failure
 endif
 
@@ -66,7 +66,7 @@ endif
 
 cd $srcdir
 if ($status != 0) then
-    logger -t $myname"[$$]" -p user.info "ERROR: can't chdir $srcdir"
+    logger -t $myname"[$$]" -p local0.info "ERROR: can't chdir $srcdir"
     goto failure
 endif
 
@@ -76,10 +76,10 @@ touch $dummy
 foreach file ([4-9]???????????????????????.gz [4-9]???????????????????????.GZ)
     if ($file != $dummy) then
         set command = "cp -p $file $dstdir"
-        if ($debug) logger -t $myname"[$$]" -p user.info "$command"
+        if ($debug) logger -t $myname"[$$]" -p local0.info "$command"
         $command
         if ($status != 0) then
-            logger -t $myname"[$$]" -p user.info "FAILED: $command"
+            logger -t $myname"[$$]" -p local0.info "FAILED: $command"
             rm $dummy
             goto failure
         endif
@@ -91,11 +91,11 @@ rm -f $dummy
 # Normal exit
 
 success:
-if ($debug) logger -t $myname"[$$]" -p user.info "completed OK"
+if ($debug) logger -t $myname"[$$]" -p local0.info "completed OK"
 exit 0
 
 failure:
-logger -t $myname"[$$]" -p user.info "exit 1"
+logger -t $myname"[$$]" -p local0.info "exit 1"
 exit 1
 
 # Revision History
diff --git a/scripts/isiStageZipFiles b/scripts/isiStageZipFiles
--- a/scripts/isiStageZipFiles
+++ b/scripts/isiStageZipFiles
@@ -6,7 +6,7 @@
 set debug  = 0
 set myname = isiStageZipFiles
 
-if ($debug) logger -t $myname"[$$]" -p user.info "begin"
+if ($debug) logger -t $myname"[$$]" -p local0.info "begin"
 
 # This only works if there is a "iso" subdir and we are
 # sitting right above it.  Special check for runs from
@@ -26,7 +26,7 @@ if (! -e $IsoDir) exit 0
 set setup  = ~nrts/scripts/ScriptSetup
 if (! -e $setup ) then
     set message = "missing $setup"
-    logger -t $myname"[$$]" -p user.info "$message"
+    logger -t $myname"[$$]" -p local0.info "$message"
     echo "${myname}: $message"
     goto failure
 endif
@@ -43,7 +43,7 @@ set errors = 0
 foreach dir ($ZipDir $StageDir $DoneZips $DoneIsos)
     if (! -d $dir) then
         set message = "Missing $dir"
-        logger -t $myname"[$$]" -p user.info "$message"
+        logger -t $myname"[$$]" -p local0.info "$message"
         echo "${myname}: $message"
         set errors = 1
     endif
@@ -58,7 +58,7 @@ set isiIsoParameters = $IsoDir/config
 foreach script ($isiCreateIsoImage $isiGenerateIsoLabel $isiIsoParameters)
     if (! -e $script) then
         set message = "Missing $script"
-        logger -t $myname"[$$]" -p user.info "$message"
+        logger -t $myname"[$$]" -p local0.info "$message"
         echo "${myname}: $message"
         set errors = 1
     endif
@@ -99,7 +99,7 @@ endif
 # If forcing an ISO image, then do it now
 
 if ($Force == TRUE) then
-    logger -t $myname"[$$]" -p user.info "begin (FORCE $StaName $PktRev $PktLen)"
+    logger -t $myname"[$$]" -p local0.info "begin (FORCE $StaName $PktRev $PktLen)"
     source $isiCreateIsoImage
     if ($status != 0) goto failure
     set count = `CountIsoImages iso`
@@ -109,7 +109,7 @@ else
     if ($MaxMBytesPerArchive == 0) set MaxMBytesPerArchive = $DefaultMaxMbytes
     @ MaxBytesPerArchive = $MaxMBytesPerArchive * 1024 * 1024
     set Force = FALSE
-    if ($debug) logger -t $myname"[$$]" -p user.info "begin ($MaxMBytesPerArchive $StaName $PktRev $PktLen)"
+    if ($debug) logger -t $myname"[$$]" -p local0.info "begin ($MaxMBytesPerArchive $StaName $PktRev $PktLen)"
 endif
 
 # Move zipped files into the staging area, building ISO images as needed
@@ -119,7 +119,7 @@ StartOfLoop:
     @ BytesUsed  = `du -sk $StageDir | awk '{print $1}'`
     @ BytesUsed *= 1024 # convert from K-bytes to bytes
     if ($BytesUsed > $MaxBytesPerArchive) then
-        logger -t $myname"[$$]" -p user.info "WARNING: $StageDir is too full"
+        logger -t $myname"[$$]" -p local0.info "WARNING: $StageDir is too full"
         source $isiCreateIsoImage
         goto StartOfLoop
     endif
@@ -127,7 +127,7 @@ StartOfLoop:
 
     # Move files from the zip directory to the staging directory
 
-    if ($debug) logger -t $myname"[$$]" -p user.info "staging files from $ZipDir to $StageDir"
+    if ($debug) logger -t $myname"[$$]" -p local0.info "staging files from $ZipDir to $StageDir"
     set dummy = $ZipDir/Dummy.gz
     touch $dummy
     chmod 777 $dummy
@@ -138,22 +138,22 @@ StartOfLoop:
             if ($file == $dummy) continue
             @ FileSize = `wc -c $file | awk '{print $1}'`
             if ($FileSize > $AvailSpace) then
-                logger -t $myname"[$$]" -p user.info "$StageDir is full"
+                logger -t $myname"[$$]" -p local0.info "$StageDir is full"
                 source $isiCreateIsoImage
                 goto StartOfLoop
             else
                 set command = "mv $file $StageDir"
-                if ($debug) logger -t $myname"[$$]" -p user.info "$command"
+                if ($debug) logger -t $myname"[$$]" -p local0.info "$command"
                 $command
                 if ($status == 0) then
                     @ AvailSpace -= $FileSize
                     if ($AvailSpace <= 0) then
-                        logger -t $myname"[$$]" -p user.info "$StageDir is full"
+                        logger -t $myname"[$$]" -p local0.info "$StageDir is full"
                         source $isiCreateIsoImage
                         goto StartOfLoop
                     endif
                 else
-                    logger -t $myname"[$$]" -p user.info "FAILED: $command"
+                    logger -t $myname"[$$]" -p local0.info "FAILED: $command"
                     goto failure
                 endif
             endif
@@ -164,12 +164,12 @@ StartOfLoop:
 
 success:
 pkill -HUP -x ispd
-if ($debug) logger -t $myname"[$$]" -p user.info "completed OK"
+if ($debug) logger -t $myname"[$$]" -p local0.info "completed OK"
 exit 0
 
 failure:
 pkill -HUP -x ispd
-logger -t $myname"[$$]" -p user.info "exit 1"
+logger -t $myname"[$$]" -p local0.info "exit 1"
 exit 1
 
 # Revision History
