log to local0.info; add '--bounce' option to trigger 'bounce' of all tunnels prior to 'check'; implement BounceTunnels code in-line, rendering BounceTunnels script obsolete

diff --git a/scripts/CheckTunnels b/scripts/CheckTunnels
--- a/scripts/CheckTunnels
+++ b/scripts/CheckTunnels
@@ -1,5 +1,4 @@
 #!/bin/csh -f
-# "$Id: CheckTunnels,v 1.11 2017/10/31 18:33:43 dechavez Exp $"
 #
 # Manage SSH tunnels
 
@@ -8,14 +7,14 @@ set myname = CheckTunnels
 set lock   = /var/tmp/$myname.lock
 set match  = /var/tmp/$myname.matches.$$
 
-if ($debug) logger -t $myname"[$$]" -p user.info "begin"
+if ($debug) logger -t $myname"[$$]" -p local0.info "begin"
 
 # General setup
 
 set setup  = ~nrts/scripts/ScriptSetup
 if (! -e $setup ) then
     set message = "missing $setup"
-    logger -t $myname"[$$]" -p user.info "$message"
+    logger -t $myname"[$$]" -p local0.info "$message"
     echo "${myname}: $message"
     exit 1
 endif
@@ -31,28 +30,38 @@ set TunnelPorts  = $NRTS_HOME/etc/Tunnels
 set TunnelPeers  = $NRTS_HOME/etc/TunnelPeers
 set default_peer = idahub
 
-# The local data and SSH port numbers may be overridden on the command line
-# Single argument is assumed to be port number for the data service
-
-if ($#argv > 0) then
-    set LocalData = $argv[1]
-    shift
-endif
-
-# Second argument (if it exists) is assumed to be the local ssh port
-
-if ($#argv > 0) then
-    set LocalShell = $argv[1]
-    shift
-endif
-
-# More than two arguments is not allowed
-
-if ($#argv != 0) then
+#More than one argument is not allowed
+if ($#argv > 1) then
     set message = "${myname}: unrecognized argument(s): $argv"
     echo $message
-    if ($debug) logger -t $myname"[$$]" -p user.info "unrecognized argument(s): $argv"
+    if ($debug) logger -t $myname"[$$]" -p local0.info "unrecognized argument(s): $argv"
     exit 1
+endif
+
+# Single argument is assumed option flag to force a tunnel bounce
+if ($#argv == 1) then
+    if ($argv[1] == "--bounce") then
+        if ($debug) logger -t $myname"[$$]" -p local0.info "bounce option triggering kill of all ssh tunnels"
+
+        set list = `/bin/ps -ax -o pid,user,command | egrep "nrts +ssh -f -N" | awk '{print $1}'`
+        foreach pid ($list)
+
+            if ($debug) then
+                set cmd = `ps -p $pid -o command | grep -v COMMAND`
+                logger -t $myname"[$$]" -p local0.debug "Bouncing tunnel:[${pid}] $cmd"
+            endif
+
+            kill -TERM $pid  >& /dev/null
+
+            if ($debug) logger -t $myname"[$$]" -p local0.debug "Bounced: [${pid}]"
+
+        end
+    else
+        set message = "${myname}: unrecognized argument(s): $argv"
+        echo $message
+        if ($debug) logger -t $myname"[$$]" -p local0.info "unrecognized argument(s): $argv"
+        exit 1
+    endif
 endif
 
 # Tunnel endpoint is idahub, unless more or alternate destinations
@@ -66,7 +75,7 @@ endif
 
 # Get the port numbers from the lookup table
 if (! -e $TunnelPorts) then
-    if ($debug) logger -t $myname"[$$]" -p user.info "$TunnelPorts not present"
+    if ($debug) logger -t $myname"[$$]" -p local0.info "$TunnelPorts not present"
     exit 1
 endif
 
@@ -74,7 +83,7 @@ endif
 stripcat $TunnelPorts | grep -i " $TunnelName " > $match
 set exitstatus = $status
 if ($exitstatus != 0) then
-    if ($debug) logger -t $myname"[$$]" -p user.info "can't extract ports for $TunnelName from $TunnelPorts"
+    if ($debug) logger -t $myname"[$$]" -p local0.info "can't extract ports for $TunnelName from $TunnelPorts"
     rm -rf $match
     exit 1
 endif
@@ -85,7 +94,7 @@ rm -rf $match
 
 filelock $lock $$
 if ($status != 0) then
-    if ($debug) logger -t $myname"[$$]" -p user.info "another instance already active"
+    if ($debug) logger -t $myname"[$$]" -p local0.info "another instance already active"
     rm -rf $match
     exit 0
 endif
@@ -132,20 +141,20 @@ foreach RemoteHost ($RemoteHostList)
                 set LocalData = $PortString[6]
                 set LocalShell = $PortString[7]
             else 
-                if ($debug) logger -t $myname"[$$]" -p user.info "can't find $TunnelName in invalid record $PortString"
+                if ($debug) logger -t $myname"[$$]" -p local0.info "can't find $TunnelName in invalid record $PortString"
             endif
 
         else
-            if ($debug) logger -t $myname"[$$]" -p user.info "invalid record $PortString"
+            if ($debug) logger -t $myname"[$$]" -p local0.info "invalid record $PortString"
             continue
         endif
 
-        if ($debug) logger -t $myname"[$$]" -p user.info "LocalData = $LocalData"
-        if ($debug) logger -t $myname"[$$]" -p user.info "LocalShell = $LocalShell"
-        if ($debug) logger -t $myname"[$$]" -p user.info "RemoteData = $RemoteData"
-        if ($debug) logger -t $myname"[$$]" -p user.info "RemoteShell = $RemoteShell"
-        if ($debug) logger -t $myname"[$$]" -p user.info "TunnelUser = $TunnelUser"
-        if ($debug) logger -t $myname"[$$]" -p user.info "TunnelHost = $TunnelHost"
+        if ($debug) logger -t $myname"[$$]" -p local0.info "LocalData = $LocalData"
+        if ($debug) logger -t $myname"[$$]" -p local0.info "LocalShell = $LocalShell"
+        if ($debug) logger -t $myname"[$$]" -p local0.info "RemoteData = $RemoteData"
+        if ($debug) logger -t $myname"[$$]" -p local0.info "RemoteShell = $RemoteShell"
+        if ($debug) logger -t $myname"[$$]" -p local0.info "TunnelUser = $TunnelUser"
+        if ($debug) logger -t $myname"[$$]" -p local0.info "TunnelHost = $TunnelHost"
 
         logger -t $myname"[$$]" -p user.notice "Starting SSH tunnels into $RemoteHost"
         # NOTE: Do not change the order of the ssh parameters without consider BounceTunnels
@@ -156,7 +165,7 @@ foreach RemoteHost ($RemoteHostList)
 
         pgrep -f "$command" >& /dev/null
         if ($status == 0) then
-            if ($debug) logger -t $myname"[$$]" -p user.info "tunnel already present"
+            if ($debug) logger -t $myname"[$$]" -p local0.info "tunnel already present"
         else
             # Launch the tunnel
             $command
@@ -167,43 +176,3 @@ end
 
 exit 0
 
-# Revision History
-#
-# $Log: CheckTunnels,v $
-# Revision 1.11  2017/10/31 18:33:43  dechavez
-# move the user@host part to the front of the command to support "pid tunnel" on small screens (yes, that's true)
-# changed MyData and MyShell to LocalData and LocalShell
-#
-# Revision 1.10  2017/07/06 21:04:20  dauerbach
-# Use entire ssh command when checking to see if tunnels already exist
-#
-# Revision 1.9  2015/12/10 00:00:15  dechavez
-# undid the previous change, now use ~nrts instead of NRTS_HOME to load the setup script
-# (didn't work in cron, duh)
-#
-# Revision 1.8  2015/12/07 22:18:43  dechavez
-# don't assume user nrts (use NRTS_HOME environment varible instead)
-#
-# Revision 1.7  2013/10/25 21:10:08  dechavez
-# reorded stuff so that the path is right when invoked via cron
-#
-# Revision 1.6  2013/10/25 17:17:40  dechavez
-# change from hard-coded list of peers to optional ~/etc/TunnelPeers
-#
-# Revision 1.5  2013/08/07 17:38:55  dechavez
-# fixed restart problem when one of two tunnels was present
-#
-# Revision 1.4  2013/07/26 22:05:11  dechavez
-# set up tunnels to both idahub and pidahub
-#
-# Revision 1.3  2012/12/05 21:15:37  dechavez
-# Change target key to be hostname instead of default site (allows for more
-# than one computer per site to tunnel into idahub), and allow for the local
-# data and ssh ports to get assigned on the command line.
-#
-# Revision 1.2  2008/05/06 20:44:48  dechavez
-# use pgrep -f to check for existing tunnels
-#
-# Revision 1.1  2008/05/06 20:29:13  dechavez
-# created
-#
