change user.info to local0.info; remove old CVS revision histories

diff --git a/scripts/isiStageTeeFiles b/scripts/isiStageTeeFiles
--- a/scripts/isiStageTeeFiles
+++ b/scripts/isiStageTeeFiles
@@ -8,19 +8,19 @@ set myname = isiStageTeeFiles
 set tmp1 = /tmp/$myname.tmp1.$$
 set tmp2 = /tmp/$myname.tmp2.$$
 
-if ($debug) logger -t $myname"[$$]" -p user.info "begin"
+if ($debug) logger -t $myname"[$$]" -p local0.info "begin"
 
 # General setup
 
 set setup  = ~nrts/scripts/ScriptSetup
 if (! -e $setup ) then
     set message = "missing $setup"
-    logger -t $myname"[$$]" -p user.info "$message"
+    logger -t $myname"[$$]" -p local0.info "$message"
     echo "${myname}: $message"
     goto failure
 endif
 source $setup
-if ($debug) logger -t $myname"[$$]" -p user.info "$setup OK"
+if ($debug) logger -t $myname"[$$]" -p local0.info "$setup OK"
 
 # Command line setup
 
@@ -52,7 +52,7 @@ endif
 
 if ($error) then
     set message = "bad command line, error $error"
-    logger -t $myname"[$$]" -p user.info "$message"
+    logger -t $myname"[$$]" -p local0.info "$message"
     echo "${myname}: $message"
     echo "usage: $myname [ FORCE ] [ site ]"
     goto failure
@@ -77,28 +77,28 @@ if (! -e $IsoDir) goto success
 filelock $LockFile $$
 if ($status != 0) then
     set active = `cat $LockFile`
-    if ($debug) logger -t $myname"[$$]" -p user.info "ISO directory locked by process $active"
+    if ($debug) logger -t $myname"[$$]" -p local0.info "ISO directory locked by process $active"
     goto success
 endif
 
 # Nothing to do if there isn't a tee directory
 
 if (! -d $TeeDir) then
-    if ($debug) logger -t $myname"[$$]" -p user.info "no such tee dir $TeeDir"
+    if ($debug) logger -t $myname"[$$]" -p local0.info "no such tee dir $TeeDir"
     goto success
 endif
 
 # Nothing to do if the STOP flag is set in the tee directory
 
 if (-e $StopFlag) then
-    if ($debug) logger -t $myname"[$$]" -p user.info "quit: $site STOP flag set"
+    if ($debug) logger -t $myname"[$$]" -p local0.info "quit: $site STOP flag set"
     goto success
 endif
 
 # Nothing to do if there isn't a iso directory
 
 if (! -d $IsoDir) then
-    if ($debug) logger -t $myname"[$$]" -p user.info "no such iso dir $IsoDir"
+    if ($debug) logger -t $myname"[$$]" -p local0.info "no such iso dir $IsoDir"
     goto success
 endif
 
@@ -113,7 +113,7 @@ set errors = 0
 foreach dir ($StageDir $DoneZips $DoneIsos)
     if (! -d $dir) then
         set message = "Missing $dir"
-        logger -t $myname"[$$]" -p user.info "$message"
+        logger -t $myname"[$$]" -p local0.info "$message"
         echo "${myname}: $message"
         set errors = 1
     endif
@@ -129,7 +129,7 @@ set isiIsoParameters = $IsoDir/config
 foreach script ($isiPurgeOldImages $isiCreateIsoImage $isiGenerateIsoLabel $isiIsoParameters)
     if (! -e $script) then
         set message = "Missing $script"
-        logger -t $myname"[$$]" -p user.info "$message"
+        logger -t $myname"[$$]" -p local0.info "$message"
         echo "${myname}: $message"
         set errors = 1
     endif
@@ -153,9 +153,9 @@ source $isiIsoParameters
 # If forcing an ISO image, then do it now
 
 if ($Force) then
-    logger -t $myname"[$$]" -p user.info "FORCE $StaName $PktRev $PktLen"
+    logger -t $myname"[$$]" -p local0.info "FORCE $StaName $PktRev $PktLen"
     source $isiCreateIsoImage
-    if ($debug) logger -t $myname"[$$]" -p user.info "isiCreateIsoImage status $status"
+    if ($debug) logger -t $myname"[$$]" -p local0.info "isiCreateIsoImage status $status"
     if ($status != 0) goto failure
     set count = `ls $IsoDir | grep ".iso" | wc -l`
     echo "$count ISO images ready to copy"
@@ -163,7 +163,7 @@ if ($Force) then
 else
     @ MaxMBytesPerArchive = $DefaultMaxMbytes
     @ MaxBytesPerArchive = $MaxMBytesPerArchive * 1024 * 1024
-    if ($debug) logger -t $myname"[$$]" -p user.info "begin ($MaxMBytesPerArchive $StaName $PktRev $PktLen)"
+    if ($debug) logger -t $myname"[$$]" -p local0.info "begin ($MaxMBytesPerArchive $StaName $PktRev $PktLen)"
 endif
 
 # Compress all but the most recent uncompressed tee file
@@ -176,24 +176,24 @@ if ($status == 0) then
     if ($NumFiles <= 0) goto success
     @ NumFiles -= 1
     if ($NumFiles != 0) then
-        if ($debug) logger -t $myname"[$$]" -p user.info "compressing files in $TeeDir"
+        if ($debug) logger -t $myname"[$$]" -p local0.info "compressing files in $TeeDir"
         set UncompressedFileList = `head -$NumFiles $tmp1`
         if ($status == 0) then
             foreach file ($UncompressedFileList)
                 set output = $file.gz
                 rm -f $output
                 set command = "gzip $file"
-                if ($debug) logger -t $myname"[$$]" -p user.info "$command"
+                if ($debug) logger -t $myname"[$$]" -p local0.info "$command"
                 $command
                 if (-e $file && -e $output) then
-                    logger -t $myname"[$$]" -p user.info "$command failed"
+                    logger -t $myname"[$$]" -p local0.info "$command failed"
                     rm -f $output
                     goto failure
                 endif
             end
         endif
     else
-        if ($debug) logger -t $myname"[$$]" -p user.info "nothing pending compression in $TeeDir"
+        if ($debug) logger -t $myname"[$$]" -p local0.info "nothing pending compression in $TeeDir"
     endif
 endif
 
@@ -204,7 +204,7 @@ StartOfLoop:
     @ BytesUsed  = `du -sk $StageDir | awk '{print $1}'`
     @ BytesUsed *= 1024 # convert from K-bytes to bytes
     if ($BytesUsed > $MaxBytesPerArchive) then
-        logger -t $myname"[$$]" -p user.info "WARNING: $StageDir is too full"
+        logger -t $myname"[$$]" -p local0.info "WARNING: $StageDir is too full"
         source $isiCreateIsoImage
         goto StartOfLoop
     endif
@@ -212,30 +212,30 @@ StartOfLoop:
 
     # Move these files into the iso stage 
 
-    if ($debug) logger -t $myname"[$$]" -p user.info "staging files from $TeeDir to $StageDir"
+    if ($debug) logger -t $myname"[$$]" -p local0.info "staging files from $TeeDir to $StageDir"
     ls [4-9]???????????????????????.gz >& $tmp2
     if ($status == 0) then
         set CompressedFileList = `cat $tmp2`
         foreach file ($CompressedFileList)
             @ FileSize = `wc -c $file | awk '{print $1}'`
             if ($FileSize > $AvailSpace) then
-                logger -t $myname"[$$]" -p user.info "$StageDir is full"
+                logger -t $myname"[$$]" -p local0.info "$StageDir is full"
                 source $isiCreateIsoImage
                 goto StartOfLoop
             else
                 set destpath = `uniqpath suflen=3 $file $StageDir`
                 set command = "mv $file $destpath"
-                if ($debug) logger -t $myname"[$$]" -p user.info "$command"
+                if ($debug) logger -t $myname"[$$]" -p local0.info "$command"
                 $command
                 if ($status == 0) then
                     @ AvailSpace -= $FileSize
                     if ($AvailSpace <= 0) then
-                        logger -t $myname"[$$]" -p user.info "$StageDir is full"
+                        logger -t $myname"[$$]" -p local0.info "$StageDir is full"
                         source $isiCreateIsoImage
                         goto StartOfLoop
                     endif
                 else
-                    logger -t $myname"[$$]" -p user.info "FAILED: $command"
+                    logger -t $myname"[$$]" -p local0.info "FAILED: $command"
                     goto failure
                 endif
             endif
@@ -248,80 +248,13 @@ success:
 rm -f $tmp1
 rm -f $tmp2
 pkill -HUP -x ispd
-if ($debug) logger -t $myname"[$$]" -p user.info "completed OK"
+if ($debug) logger -t $myname"[$$]" -p local0.info "completed OK"
 exit 0
 
 failure:
 rm -f $tmp1
 rm -f $tmp2
 pkill -HUP -x ispd
-logger -t $myname"[$$]" -p user.info "exit 1"
+logger -t $myname"[$$]" -p local0.info "exit 1"
 exit 1
 
-# Revision History
-#
-# $Log: isiStageTeeFiles,v $
-# Revision 1.20  2015/12/10 00:00:16  dechavez
-# undid the previous change, now use ~nrts instead of NRTS_HOME to load the setup script
-# (didn't work in cron, duh)
-#
-# Revision 1.19  2015/12/07 22:18:43  dechavez
-# don't assume user nrts (use NRTS_HOME environment varible instead)
-#
-# Revision 1.18  2014/08/15 16:21:29  dechavez
-# Removed requirement that site name be explictly inluded in multi-site systems.
-# Now it we just use the default site in that case.
-#
-# Revision 1.17  2013/09/20 17:03:08  dechavez
-# call isiPurgeOldImages to keep the number of unburned images managable
-#
-# Revision 1.16  2012/07/30 23:25:54  dechavez
-# fixed bug about file names starting with 4 failing after July 14, 2012
-#
-# Revision 1.15  2008/03/19 21:01:16  dechavez
-# clean exit on no ISO dir
-#
-# Revision 1.14  2008/03/19 19:42:30  dechavez
-# say "copy" instead of "burn"
-#
-# Revision 1.13  2008/03/13 21:36:10  dechavez
-# use filelock for instance locking
-#
-# Revision 1.12  2008/03/12 21:08:17  dechavez
-# improved self detection
-#
-# Revision 1.11  2008/02/01 22:59:15  dechavez
-# use pgrep -x to locate multiple instances of self, made special branch
-# to handle case of no files ready for compression (head -0 caused problems
-# on some platform)
-#
-# Revision 1.10  2007/05/16 17:38:56  dechavez
-# require user to specify explicit site name for multi-site systems
-#
-# Revision 1.9  2006/04/08 03:55:16  dechavez
-# define tmp files at startup in case of very early exit
-#
-# Revision 1.8  2006/04/07 22:59:33  dechavez
-# yet another rushed fix, now to deal with the case of no .gz files
-#
-# Revision 1.7  2006/04/07 22:29:19  dechavez
-# remove tmp file (duh)
-#
-# Revision 1.6  2006/04/07 17:00:32  dechavez
-# handle the case of one or more pre-existing .gz files
-#
-# Revision 1.5  2006/04/06 16:56:01  dechavez
-# .nozip support
-#
-# Revision 1.4  2005/10/20 20:05:10  dechavez
-# added debug tracer
-#
-# Revision 1.3  2005/10/12 00:21:01  dechavez
-# fixed error counting number of images ready to burn after Force
-#
-# Revision 1.2  2005/10/11 18:18:37  dechavez
-# fixed command line parsing
-#
-# Revision 1.1  2005/10/11 00:03:19  dechavez
-# initial release
-#
